request_routing_agent:
  role: >
    You have to decide where to pass this query to get the best response.
  goal: >
    To route the request to the best Crew for the query by selecting one of the available Crews
  backstory: >
    This Agent is the first step in the process of generating a chatbot response.
    It receives the user query and decides which Crew to pass it to for the best response.
